### ISSUE TITLE
Add Serialize/Deserialize capability to `NonEmpty`

### ISSUE THREAD

**Issue by U007D** [cloudhead/nonempty#25]
I am using `NonEmpty` in a structure which gets serialized to bytes for hashing purposes.  I thought it would be best to implement this and give back as https://github.com/cloudhead/nonempty/pull/24.

Note, I wasn't sure how you wanted to manage the (feature-gated) `serde` dependency, so left it at the default setting of the current version in `Cargo.toml`: (`version = "1.0.111"`).  It *might* be preferable to allow any compatible version (`version = "1"`)...

**Comment by cloudhead** [comment]
Fixed in #24
