### ISSUE TITLE
Add `NonEmpty::capacity`

### ISSUE THREAD

**Issue by str4d** [cloudhead/nonempty#33]
Analogue of `Vec::capacity` to indicate how many items the `NonEmpty` can hold without reallocating. My use case for this is determining the dynamic memory usage of a structure that contains a `NonEmpty<T>`; with this API, I could calculate it as `(non_empty_vec.capacity() - 1) * size_of::<T>()`.

**Comment by cloudhead** [comment]
Yeah, piece of cake. Give me a sec.

**Comment by cloudhead** [comment]
Fixed in 21641169e4e7cefd2f7306b3262528135e4ab0b5

**Comment by cloudhead** [comment]
v0.7.0 is published, have fun!
