### ISSUE TITLE
Feature Request: Getting the length as NonZeroUsize

### ISSUE THREAD

**Issue by GnomedDev** [cloudhead/nonempty#47]
A method to get the length of the NonEmpty as a NonZeroUsize would be useful and improve ergonomics. It surprises me that `len` doesn't already return NonZeroUsize, but to prevent breaking it should probably be a separate method.

**Comment by cloudhead** [comment]
The reason for returning `usize` was compatibility with the other collections in stdlib, but indeed what you propose would be nice. There are several options:

1. Change it to `NonZeroUsize` (breaking change, so bump the version)
2. Have a feature flag that is off by default, and changes the output to `NonZeroUsize`
3. Have a different method, eg. `nonzero_len(&self) -> NonZeroUsize`

**Comment by cloudhead** [comment]
I probably would be in favor of (2), since it's a specific use-case that some people may not be interested in, but can be activated for those who want it.

**Comment by GnomedDev** [comment]
I disagree that 2 would be a good idea, features are meant to always be additive and not change behavior as they are unified between crates, so a downstream crate could enable the non_zero feature and break others in one tree. I stand by 3 being the best idea as it fulfills the opt-in behavior you want while having no downsides other than a slightly longer method name.

**Comment by cloudhead** [comment]
You're right yes, I hadn't thought of that.

**Comment by cloudhead** [comment]
Merged your #50 - thanks.
