### ISSUE TITLE
SmallNonEmpty?

### ISSUE THREAD

**Issue by tesujimath** [cloudhead/nonempty#49]
I am finding a need for `SmallNonEmpty`, which would be this:

```
pub struct SmallNonEmpty<A>
where
    A: smallvec::Array,
{
    pub head: A::Item,
    pub tail: smallvec::SmallVec<A>,
}
```

using the [smallvec](https://docs.rs/smallvec/latest/smallvec/) crate.

I had a look at what would be required here, besides a `small` feature for this crate.  Introducing a layer of indirection though a `VecLike` trait (to abstract away from the difference between `Vec` and `SmallVec`) and a `NonEmptyLike` trait (to allow for default implementations of the functions which would be common between `NonEmpty` and `SmallNonEmpty`) seems like more work than would be reasonable.

A far easier approach would be separate implementations to match what we have for `NonEmpty`, but that seems a bit crass.

Does such a thing even belong in this crate?

(For now I am implementing what I need in my own crate, but happy to contribute here if that would be appropriate.)

Interested in your thoughts!

**Comment by FintanH** [comment]
@fosskers has made a lovely crate that houses a lot of non-empty collections with non-empty iterators -- (nonempty-collections)[https://crates.io/crates/nonempty-collections). It might find a better home there but there would still be some manual work to fit it in there. There was also some nice sketches of nonempty collections in [`radicle-link/data`](https://github.com/radicle-dev/radicle-link/tree/master/data/src) that might be interesting for defining more generic ways of building and using nonempty collections

**Comment by tesujimath** [comment]
Thanks!  I'll have a look at those.
