### ISSUE TITLE
`nonempty!` macro doesn't allow trailing comma

### ISSUE THREAD

**Issue by urmaul** [cloudhead/nonempty#51]
I'd like to write something like:

~~~rust
let a = nonempty![
    1,
    2,
    3,
];
~~~

But the compiler doesn't allow it.

**Comment by FintanH** [comment]
[This should be fixed](https://github.com/cloudhead/nonempty/pull/46), but perhaps hasn't been pushed to crates.io. @cloudhead should we push a new semver?

**Comment by cloudhead** [comment]
It is merged and pushed already
