### ISSUE TITLE
Support for Arbitrary

### ISSUE THREAD

**Issue by greyblake** [cloudhead/nonempty#53]
Hi, thank you for the nice and helpful crate!

Would you consider adding support for [Arbitrary](https://docs.rs/arbitrary/latest/arbitrary/trait.Arbitrary.html) behind a feature flag?

Thank you!

**Comment by AlisCode** [comment]
Relevant documentation : 

* https://docs.rs/arbitrary/latest/src/arbitrary/lib.rs.html#678-691 implementation of Arbitrary for `Vec<A>` where `A: Arbitrary`
* https://docs.rs/arbitrary/latest/arbitrary/unstructured/struct.Unstructured.html#method.arbitrary_iter

**Comment by FintanH** [comment]
Huh, TIL about `arbitrary`. I guess my question would be if it's worth maintaining this? It would probably be lightweight since I imagine the code would be fairly straightforward, but we'd also need to maintain the versioning.

Is defining your own helper possible? e.g.

```rust
pub fn nonempty<T: Arbitrary>(&mut u: Unstructured) -> NonEmpty<T> {
  let head = u.arbitrary();
  let tail = u.arbitrary();
  NonEmpty { head, tail }
}
```

**Comment by greyblake** [comment]
> I guess my question would be if it's worth maintaining this? 

I think yes.
It's more or less becoming a common standard for crates implement `Arbitrary`.
It's supported by many popular libraries like `chorno`, `uuid`, `smallvec`.

There is not much to maintain, it would be roughly the implementation you suggested.


> Is defining your own helper possible? e.g.
It's possible, though it's not so convient as having it implemented directly for NonEmpty

**Comment by AlisCode** [comment]
Yeah I think the implementation is pretty straightforward. I'll have a go at this today. 

> but we'd also need to maintain the versioning.

I understand the concern, but I dont really think this is an issue given that Arbitrary has already reached 1.0. The API is unlikely to change significantly.
