### ISSUE TITLE
`split` method is ambiguous on its own

### ISSUE THREAD

**Issue by mx00s** [cloudhead/nonempty#60]
Calling `split` on a single-element `NonEmpty` returns the same thing as a two-element `NonEmpty` when all the elements are the same.

```rust
    #[test]
    fn non_empty_split() {
        let one_element: NonEmpty<i32> = NonEmpty {
            head: 0,
            tail: vec![],
        };
        assert_eq!(one_element.len(), 1);

        let two_elements: NonEmpty<i32> = NonEmpty {
            head: 0,
            tail: vec![0],
        };
        assert_eq!(two_elements.len(), 2);

        // This assertion fails because they return the same thing, namely `(0, &[], 0)`!
        assert_ne!(one_element.split(), two_elements.split());
    }
```

Although this situation can be disambiguated, e.g. by checking the length, it's a potential source of confusion and bugs.

Changing the return type to `(&T, &[T], Option<&T>)` and returning `(0, &[], None)` for the one-element case and `(0, &[], Some(0))` for the two-element case would resolve the ambiguity.

**Comment by FintanH** [comment]
That makes sense :+1: I'll add a patch to change it to return `Option` for the last element
